# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: conversao-temperatura
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: web
#   template:
#     metadata:
#       labels:
#         app: web
#     spec:
#       containers:
#         - name: conversao-temperatura-web
#           image: robriek/conversao-temperatura:v1
#           ports:
#             - containerPort: 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-page
          image: robriek/conversao-temperatura:v1
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector: 
    app: web
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  type: NodePort